### ISSUE TITLE
Missing open source license

### ISSUE THREAD

**Issue by platisd** [netom/android-network-service-discovery#1]
Hi,

Great app. In Play Store you mention that it is free, without ads and open source. It is indeed free and without ads however it is not open source until it is published with an open source license. Can you [please choose one](https://choosealicense.com/) for your project and add it? Otherwise no one is able to use it.

Thanks!

**Comment by netom** [comment]
Hello,
thanks, I simply forgot to add the MIT license. Will do in a minute.
Cheers!

**Comment by platisd** [comment]
Thanks! :+1:
